services:
  hook:
    build: .
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - WEBHOOK_SECRET=${WEBHOOK_SECRET}
      - PANGOLIN_API_KEY=${PANGOLIN_API_KEY}
      - PANGOLIN_ORG_ID=${PANGOLIN_ORG_ID}
      - PANGOLIN_MAIN_SITE_NAME=${PANGOLIN_MAIN_SITE_NAME}
      - PANGOLIN_API_BASE_URL=${PANGOLIN_API_BASE_URL}
