on:
  push:
    branches:
      - main
    tags-ignore:
      - "**"

permissions:
  contents: write
  issues: write
  pull-requests: write

name: Release

env:
  TZ: Europe/Paris

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-release
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  typescript:
    uses: ./.github/workflows/typescript.yaml

  release-please:
    runs-on: ubuntu-latest
    needs: typescript
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      tag_name: ${{ steps.release.outputs.tag_name }}
    steps:
      - id: release
        uses: googleapis/release-please-action@v4
        with:
          release-type: simple
