on:
  push:
    branches:
      - main
    tags-ignore:
      - "**"

permissions:
  contents: write
  issues: write
  pull-requests: write

name: Release

env:
  TZ: Europe/Paris

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-release
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        with:
          release-type: simple
