name: Typescript

on:
  pull_request:
  workflow_call:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-typescript
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

env:
  TZ: Europe/Paris

jobs:
  typescript:
    name: TypeScript
    runs-on: ubuntu-latest
    env:
      PORT: 3000
    steps:
      - uses: actions/checkout@v5

      - name: Setup bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.3.10

      - name: Install dependencies
        run: bun install --frozen-lockfile --ignore-scripts

      - name: Linting
        run: bun run lint

      - name: Type check
        run: bun run check

      - name: Build
        run: bun run build

      - name: Test
        run: bun test

      # - name: Extract coverage percentage
      #   if: github.ref == 'refs/heads/main'
      #   id: coverage
      #   run: |
      #     LH=$(grep -h "^LH:" coverage/lcov.info | awk -F: '{sum+=$2} END {print sum}')
      #     LF=$(grep -h "^LF:" coverage/lcov.info | awk -F: '{sum+=$2} END {print sum}')
      #     PCT=$(echo "scale=1; $LH * 100 / $LF" | bc)
      #     echo "pct=$PCT" >> $GITHUB_OUTPUT

      # - name: Update coverage badge
      #   if: github.ref == 'refs/heads/main'
      #   uses: Schneegans/dynamic-badges-action@v1.7.0
      #   with:
      #     auth: ${{ secrets.GIST_TOKEN }}
      #     gistID: ${{ vars.GIST_ID }}
      #     filename: coverage.json
      #     label: coverage
      #     message: ${{ steps.coverage.outputs.pct }}%
      #     valColorRange: ${{ steps.coverage.outputs.pct }}
      #     maxColorRange: 100
      #     minColorRange: 0
